ALTER TABLE question MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `user` MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE question MODIFY COLUMN creator BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comment MODIFY COLUMN commentator BIGINT NOT NULL DEFAULT 0;